spring:
  application:
    name: bigproject
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bigproject}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

app:
  upload-dir: ${UPLOAD_DIR:./uploads}
  s3:
    bucket: aivle-test-ai-34178924
    region: ap-northeast-2
    access-key: "임시"
    secret-key: "임시"